server:
  port: 8080

spring:
  application:
    name: api-gateway
  
  # SOLUTION AU PROBLÈME LOCALHOST : Importation explicite du serveur de config
  config:
    import: "optional:configserver:http://config-server:8888"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ticketflow
          jwk-set-uri: http://keycloak:8180/realms/ticketflow/protocol/openid-connect/certs

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        # User Service
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/roles/**, /api/permissions/**
          filters:
            - StripPrefix=1
        - id: user-service-swagger
          uri: lb://user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - StripPrefix=1

        # Ticket Service
        - id: ticket-service-route
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**
        - id: ticket-service-swagger
          uri: lb://ticket-service
          predicates:
            - Path=/ticket-service/v3/api-docs
          filters:
            - StripPrefix=1

        # Notification Service
        - id: notification-service-route
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**, /api/notifications
        - id: notification-service-swagger
          uri: lb://notification-service
          predicates:
            - Path=/notification-service/v3/api-docs
          filters:
            - StripPrefix=1

        # Document Service
        - id: document-service-route
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**
          filters:
            - StripPrefix=1
        - id: document-service-swagger
          uri: lb://document-service
          predicates:
            - Path=/document-service/v3/api-docs
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: "1. User Service"
        url: /user-service/v3/api-docs
      - name: "2. Ticket Service"
        url: /ticket-service/v3/api-docs
      - name: "3. Notification Service"
        url: /notification-service/v3/api-docs
      - name: "4. Document Service"
        url: /document-service/v3/api-docs

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, tracing
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/