server:
  port: 8084

spring:
  application:
    name: document-service

  datasource:
    url: jdbc:postgresql://localhost:5432/document_db
    username: postgres
    password: jjk
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ticketflow
          jwk-set-uri: http://localhost:8180/realms/ticketflow/protocol/openid-connect/certs

# Configuration MinIO
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: ticketflow-bucket

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, tracing
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/