server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://postgres:5432/ticketflow_db
    username: postgres
    password: jjk

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ticketflow
          issuer-uri: http://keycloak:8180/realms/ticketflow
          jwk-set-uri: http://keycloak:8180/realms/ticketflow/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:9092

keycloak:
  auth-server-url: http://keycloak:8180
  admin:
    username: admin
    password: admin
  realm: ticketflow
  resource: ticketflow-api
  credentials:
    secret: jnnLZSEhx5eZ4K8uEpiJmXJ4PNmjCI1V

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, tracing
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true